---
apiVersion: 1

datasources:

- name: Prometheus
  type: prometheus
  isDefault: true
  editable: true
  access: proxy
  url: http://prometheus:9090

- name: Mimir
  type: prometheus
  isDefault: false
  editable: true
  access: proxy
  url: http://mimir:9009/prometheus

- name: Loki
  type: loki
  isDefault: false
  editable: true
  access: proxy
  url: http://loki:3100
  jsonData:
    # LogQL example: {exporter="OTLP"} | json
    derivedFields:
    - name: TraceID
      datasourceUid: tempo
      matchType: label
      matcherRegex: traceid
      url: $${__value.raw}

- name: Tempo
  type: tempo
  isDefault: false
  editable: true
  access: proxy
  url: http://tempo:3200
