---
apiVersion: 1

datasources:

- name: Prometheus
  type: prometheus
  uid: prometheus_ds
  isDefault: true
  editable: true
  access: proxy
  url: http://prometheus:9090

- name: Mimir
  type: prometheus
  uid: mimir_ds
  isDefault: false
  editable: true
  access: proxy
  url: http://mimir:9009/prometheus

- name: Loki
  type: loki
  uid: loki_ds
  isDefault: false
  editable: true
  access: proxy
  url: http://loki:3100
  jsonData:
    # LogQL example: {exporter="OTLP"} | json
    derivedFields:
    - name: TraceID
      datasourceUid: tempo_ds
      matchType: label
      matcherType: label
      matcherRegex: traceid
      url: $${__value.raw}

- name: Tempo
  type: tempo
  uid: tempo_ds
  isDefault: false
  editable: true
  access: proxy
  url: http://tempo:3200
  jsonData:
    lokiSearch:
      datasourceUid: loki_ds
    tracesToLogs:
      datasourceUid: loki_ds
    serviceMap:
      datasourceUid: mimir_ds
    nodeGraph:
      enabled: true
