---
global:

  scrape_interval: 15s
  scrape_timeout: 5s

scrape_configs:

- job_name: mimir
  metrics_path: /metrics
  static_configs:
  - targets:
    - mimir:9009

- job_name: loki
  metrics_path: /metrics
  static_configs:
  - targets:
    - loki:3100

- job_name: tempo
  metrics_path: /metrics
  static_configs:
  - targets:
    - tempo:3200

- job_name: otelcol
  metrics_path: /metrics
  static_configs:
  - targets:
    - otelcol:8888
